# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: plytools/circleci-compiler:v0.2.0
    working_directory: ~/compiler
    steps:
      - checkout
      - run:
          name: Install Development 
          command: python3 setup.py develop
      - run:
          name: Compiler Test
          command: python3 -m unittest discover --verbose cloak
